### ISSUE TITLE
books and .gitignore

### ISSUE THREAD

**Issue by thorade** [jdominguezj/EVLibrary#2]
You uploaded some full books to the books directory. Was that your intention?
You should add a `.gitignore` file so that git will no longer upload e.g. the Books directoy, or those `.DS_Store` or `.bak-mo` files

**Comment by jdominguezj** [comment]
You are right,  i will add an .ignore file to avoid have them visible. 

Thank you!

**Comment by thorade** [comment]
Note that adding files/directories/file types to .gitgnore will not remove tracked files from the repository!
